#!/usr/bin/env bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH

aria2pid=$(pgrep 'aria2c')
aria2version=$(aria2c -v | head -1)

if [ ! $1 ]; then
    bash <(curl -Lsk https://cdn.jsdelivr.net/gh/Ryanjiena/Blog@master/aria2/install.aria2.sh)
    exit
fi

case $1 in
'start')
    nohup aria2c --conf-path=/root/.aria2/aria2.conf >/root/.aria2/aria2.log 2>&1 &
    exit
    ;;
'stop')
    kill -9 ${aria2pid}
    ;;
'restart')
    kill -9 ${aria2pid}
    nohup aria2c --conf-path=/root/.aria2/aria2.conf >/root/.aria2/aria2.log 2>&1 &
    exit
    ;;
'status')
    if [ "$aria2pid" == "" ]; then
        echo "Not running!"
    else
        echo '-----------------------------------------------'
        echo "Aria2 is running,pid is ${aria2pid}."
        echo '-----------------------------------------------'
    fi
    ;;
'-v')
    echo '-----------------------------------------------'
    echo "${aria2version}"
    echo "aa version 0.10"
    echo '-----------------------------------------------'
    ;;
*)
    echo '参数错误！'
    exit
    ;;
esac
